#!/usr/bin/env node

var Translator = require('./translator').Translator;
var Liner = require('./liner').Liner;

function main() {
  var args = process.argv.slice(2);
  var options = parseOptions(args);
  var phoneFile = options.phoneFile || (__dirname + '/../phone.txt');
  var wordsFile = options.wordsFile || (__dirname + '/../words.txt');
  var translator = new Translator(wordsFile, phoneFile);

  var transformLine = options.reverse ?
        translator.encode.bind(translator) :
        translator.decode.bind(translator);

  var liner = new Liner({
    transformLine: transformLine
  });

  process.stdin
    .pipe(liner)
    .pipe(process.stdout);
}

function parseOptions(args) {
  var options = {}, arg;
  arg = args.shift();

  do {
    switch(arg) {
    case '-p':
    case '--phone-file':
      arg = args.shift();
      options.phoneFile = arg;
      break;
    case '-w':
    case '--words-file':
      arg = args.shift();
      options.wordsFile = arg;
      break;
    case '-r':
    case '--reverse':
      options.reverse = true;
      break;
    case undefined:
      break;
    default:
      console.log('Unknow flag ' + arg + '.');
      process.exit(1);
    }
  } while (args.length > 0);
  return options;
}

main();
