#!/usr/bin/env ruby
class Translator
  def initialize(wordsFile, phoneFile)
    @wordsFile = wordsFile
    @phoneFile = phoneFile
    @wordsList = nil
    @l2d = nil
    @d2w = nil
  end

  def get_word_list()
    if not @wordsList
      @wordsList = []
      File.open(@wordsFile, "r") do |f|
        f.each_line do |line|
          @wordsList.push(line.rstrip)
        end
      end
    end
    return @wordsList
  end

  def get_l2d()
    if not @l2d
      @l2d = {}
      File.open(@phoneFile, "r") do |f|
        f.each_line do |line|
          digit, letters = line.split(',')
          letters.split("").each do |letter|
            @l2d[letter] = digit
          end
        end
      end
    end
    return @l2d
  end

  def encode_word(word)
    l2d = get_l2d
    word.upcase.chars.map do |letter|
      l2d.has_key?(letter) ? l2d[letter] : ""
    end.join("")
  end

  def get_d2w()
    if not @d2w
      @d2w = {}
      wl = get_word_list
      wl.each do |word|
        digits = encode_word(word)
        if not @d2w.has_key?(digits)
          @d2w[digits] = []
        end
        @d2w[digits].push(word)
      end
    end
    return @d2w
  end

  def encode(word)
    word + ": " + encode_word(word)
  end

  def decode_(digits)
    if digits.empty?
      return [[]]
    end

    d2w, res = get_d2w, []
    each_partition(digits, 1) do |partition|
      prefix, rest = partition
      if d2w.has_key?(prefix)
        first_words = d2w[prefix]
        partitial_solutions = decode_(rest)
        first_words.each do |first_word|
          partitial_solutions.each do |partial_solution|
            res.push([first_word] + partial_solution)
          end
        end
      end
    end
    return res
  end

  def decode(digits)
    decode_(digits).map do |sentence|
      digits + ": " + sentence.join(" ")
    end.join("\n")
  end

  private :get_word_list, :get_d2w, :get_l2d, :decode_
end

def each_partition(str, start=0)
  i, len = start, str.length
  while i <= len
    yield [str[0..i-1], str[i..-1]]
    i += 1
  end
end


DEFAULT_OPTIONS = {
  :wordsFile => "words.txt",
  :phoneFile => "phone.txt",
  :reverse => false
}

def parse_options(args, options=DEFAULT_OPTIONS)
  arg = args.shift
  if not arg
    options
  else
    if arg == '-w'
      options[:wordsFile] = args.shift
    elsif arg == '-p'
      options[:phoneFile] = args.shift
    elsif arg == '-r'
      options[:reverse] = true
    end
    parse_options(args, options)
  end
end

def line_by_line
  while line = gets
    yield line.rstrip
  end
end

def main
  options = parse_options(ARGV)

  translator = Translator.new(options[:wordsFile], options[:phoneFile])
  translate = options[:reverse] ? translator.method(:encode) : translator.method(:decode)

  line_by_line do |line|
    puts translate.call(line)
  end
end

main
