#!/bin/sh
pushd `dirname $0` > /dev/null && __dirname=`pwd` && popd > /dev/null

CHECK=${__dirname}/check
IMPL=$1

function join { local IFS="$1"; shift; echo "$*"; }

input_sentences_files=`ls -1 input-sentences* | sort`
output_digits_files=`ls -1 output-digits* | sort`
$CHECK ${IMPL}/translate -p phone.txt -w words.txt -r 2>/dev/null `join , ${input_sentences_files}` `join , ${output_digits_files}`

input_digits_files=`ls -1 input-digits* | sort`
output_sentences_files=`ls -1 output-sentences* | sort`
$CHECK ${IMPL}/translate -p phone.txt -w words.txt 2>/dev/null `join , ${input_digits_files}` `join , ${output_sentences_files}`
